/**
 * @fileoverview SVG Diff Engine — compares an original SVG (generated by
 * svg-render.mjs) against a user-modified SVG to produce structured changes
 * that can be translated into code edits.
 *
 * Detects:
 *   - Text changes (copy / i18n)
 *   - Rect dimension/position changes (layout)
 *   - New elements added (new components needed)
 *   - Elements removed (components to delete)
 *   - Color changes (style)
 *   - Order/position changes (reordering)
 *
 * Usage:
 *   import { diffSVG } from './runtime/svg-diff.mjs';
 *   const changes = diffSVG(originalSVG, modifiedSVG);
 *   // → { texts: [...], rects: [...], added: [...], removed: [...], ... }
 */

import { JSDOM } from 'jsdom';

/**
 * Parse SVG string into a DOM document.
 */
function parseSVG(svgString) {
  const dom = new JSDOM(svgString, { contentType: 'image/svg+xml' });
  return dom.window.document;
}

/**
 * Extract all elements with IDs from SVG document.
 * @returns {Map<string, Object>} id → { tag, attrs, text, children }
 */
function extractElements(doc) {
  const elements = new Map();
  const all = doc.querySelectorAll('[id]');
  for (const el of all) {
    const id = el.getAttribute('id');
    if (!id) continue;

    const info = {
      id,
      tag: el.tagName.toLowerCase(),
      text: el.textContent?.trim() || '',
      attrs: {},
    };

    // Extract key attributes
    for (const attr of el.attributes) {
      if (attr.name === 'id') continue;
      info.attrs[attr.name] = attr.value;
    }

    // For <g> elements, extract child rects and texts
    if (el.tagName.toLowerCase() === 'g') {
      const children = [];
      for (const child of el.children) {
        children.push({
          tag: child.tagName.toLowerCase(),
          text: child.textContent?.trim() || '',
          attrs: {},
        });
        for (const attr of child.attributes) {
          if (attr.name !== 'id') {
            children[children.length - 1].attrs[attr.name] = attr.value;
          }
        }
      }
      info.children = children;
    }

    elements.set(id, info);
  }
  return elements;
}

/**
 * Compare two values and return diff if different.
 */
function compareValues(id, key, a, b) {
  if (a === b) return null;
  return { id, property: key, from: a, to: b };
}

/**
 * Compare two SVG strings and return structured changes.
 *
 * @param {string} originalSVG
 * @param {string} modifiedSVG
 * @returns {Object} {
 *   texts: Array<{id, property, from, to}>,
 *   rects: Array<{id, property, from, to}>,
 *   added: Array<string> — ids present in modified but not original,
 *   removed: Array<string> — ids present in original but not modified,
 *   moved: Array<{id, from: {x,y}, to: {x,y}}>,
 *   summary: string
 * }
 */
export function diffSVG(originalSVG, modifiedSVG) {
  const origDoc = parseSVG(originalSVG);
  const modDoc = parseSVG(modifiedSVG);

  const origEls = extractElements(origDoc);
  const modEls = extractElements(modDoc);

  const texts = [];
  const rects = [];
  const added = [];
  const removed = [];
  const moved = [];

  // Check original elements
  for (const [id, orig] of origEls) {
    const mod = modEls.get(id);

    if (!mod) {
      removed.push(id);
      continue;
    }

    // Text content change
    if (orig.text && mod.text && orig.text !== mod.text) {
      const dataType = orig.attrs['data-type'] || mod.attrs['data-type'] || '';
      const dataLabel = orig.attrs['data-label'] || mod.attrs['data-label'] || '';
      texts.push({
        id,
        dataType,
        dataLabel,
        from: orig.text,
        to: mod.text,
        originalText: orig.attrs['data-original-text'] || orig.text,
      });
    }

    // Rect changes (position, size)
    if (orig.tag === 'rect' || (orig.children?.some(c => c.tag === 'rect'))) {
      // Check rect attributes for position/size changes
      const rectAttrs = ['x', 'y', 'width', 'height', 'rx', 'fill', 'stroke'];
      for (const attr of rectAttrs) {
        const diff = compareValues(id, attr, orig.attrs[attr], mod.attrs[attr]);
        if (diff) rects.push({ ...diff, dataType: orig.attrs['data-type'] || '', dataLabel: orig.attrs['data-label'] || '' });
      }

      // Check for position move
      if (orig.attrs.x !== mod.attrs.x || orig.attrs.y !== mod.attrs.y) {
        moved.push({
          id,
          from: { x: orig.attrs.x, y: orig.attrs.y },
          to: { x: mod.attrs.x, y: mod.attrs.y },
          dataType: orig.attrs['data-type'] || '',
          dataLabel: orig.attrs['data-label'] || '',
        });
      }
    }

    // Check child elements of groups
    if (orig.children && mod.children) {
      for (let i = 0; i < Math.min(orig.children.length, mod.children.length); i++) {
        const oc = orig.children[i];
        const mc = mod.children[i];
        if (oc.tag === 'text' && mc.tag === 'text' && oc.text !== mc.text) {
          texts.push({
            id: `${id}-child-${i}`,
            dataType: 'text',
            dataLabel: 'child text',
            from: oc.text,
            to: mc.text,
          });
        }
        if (oc.tag === 'rect' && mc.tag === 'rect') {
          for (const attr of ['x', 'y', 'width', 'height', 'fill']) {
            const diff = compareValues(`${id}-child-${i}`, attr, oc.attrs[attr], mc.attrs[attr]);
            if (diff) rects.push(diff);
          }
        }
      }
    }
  }

  // Check for new elements
  for (const [id] of modEls) {
    if (!origEls.has(id)) {
      added.push(id);
    }
  }

  // Build human-readable summary
  const summaryParts = [];
  if (texts.length > 0) summaryParts.push(`${texts.length} text changes`);
  if (rects.length > 0) summaryParts.push(`${rects.length} layout changes`);
  if (added.length > 0) summaryParts.push(`${added.length} elements added`);
  if (removed.length > 0) summaryParts.push(`${removed.length} elements removed`);
  if (moved.length > 0) summaryParts.push(`${moved.length} elements moved`);

  const summary = summaryParts.length > 0
    ? summaryParts.join(', ')
    : 'No changes detected';

  // Generate code suggestions for text changes
  const suggestions = texts.map(t => {
    if (t.dataType === 'text' && t.dataLabel?.includes('title')) {
      return `// i18n: change "${t.dataLabel}" from "${t.from}" to "${t.to}"`;
    }
    if (t.dataType === 'button' || t.dataLabel?.includes('button')) {
      return `// Button text: change "${t.dataLabel}" from "${t.from}" to "${t.to}"`;
    }
    return `// Text change: "${t.id}" from "${t.from}" to "${t.to}"`;
  });

  return {
    texts,
    rects,
    added,
    removed,
    moved,
    summary,
    suggestions,
    totalChanges: texts.length + rects.length + added.length + removed.length + moved.length,
  };
}

/**
 * Check if an SVG contains valid, parseable structure.
 */
export function validateSVG(svgString) {
  try {
    const doc = parseSVG(svgString);
    const root = doc.documentElement;
    if (!root || root.tagName.toLowerCase() !== 'svg') {
      return { valid: false, error: 'Missing <svg> root element' };
    }
    const ids = [...root.querySelectorAll('[id]')].map(el => el.getAttribute('id'));
    return { valid: true, elementCount: root.querySelectorAll('*').length, idCount: ids.length, ids };
  } catch (err) {
    return { valid: false, error: err.message };
  }
}

export default { diffSVG, validateSVG };